Repository devunionorg/PetFinderMAUI, pull requests merged in 2024-05, with the labels that each got.

#1 feature: added there pages
  PetFinderMAUI/PetFinderMAUI/App.xaml.cs
  PetFinderMAUI/PetFinderMAUI/MauiProgram.cs
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/WelcomePage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/WelcomePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
Labels: enhancement

#8 Impl firebase auth
  PetFinderMAUI/PetFinderMAUI/App.xaml.cs
  PetFinderMAUI/PetFinderMAUI/AppShell.xaml
  PetFinderMAUI/PetFinderMAUI/MainPage.xaml
  PetFinderMAUI/PetFinderMAUI/MainPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/MainPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/MainPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/WelcomePage.xaml
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
  PetFinderMAUI/PetFinderMAUI/Platforms/Android/AndroidManifest.xml
  PetFinderMAUI/PetFinderMAUI/ViewModels/LoginViewModel.cs
  PetFinderMAUI/PetFinderMAUI/ViewModels/RegisterViewModel.cs
Labels: enhancement

#13 UI improvement
  PetFinderMAUI/PetFinderMAUI/AppShell.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/FavoritePage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/FavoritePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/HomePage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/HomePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/SettingsPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/SettingsPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
Labels: enhancement

#14 Auth bugs fixed #12
  PetFinderMAUI/PetFinderMAUI/App.xaml.cs
  PetFinderMAUI/PetFinderMAUI/ViewModels/LoginViewModel.cs
Labels: bug

#18 App Identifier changed
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
Labels: enhancement

#20 UI Improvement
  PetFinderMAUI/PetFinderMAUI/MauiProgram.cs
  PetFinderMAUI/PetFinderMAUI/Pages/HomePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
Labels: enhancement

#26 Impl firebasedb
  PetFinderMAUI/PetFinderMAUI/App.xaml
  PetFinderMAUI/PetFinderMAUI/App.xaml.cs
  PetFinderMAUI/PetFinderMAUI/AppShell.xaml
  PetFinderMAUI/PetFinderMAUI/AppShell.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Entities/User.cs
  PetFinderMAUI/PetFinderMAUI/MauiProgram.cs
  PetFinderMAUI/PetFinderMAUI/Pages/FavoritePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/HomePage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/HomePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/SettingsPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/WelcomePage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/WelcomePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
  PetFinderMAUI/PetFinderMAUI/Platforms/Android/AndroidManifest.xml
  PetFinderMAUI/PetFinderMAUI/Platforms/Android/MainActivity.cs
  PetFinderMAUI/PetFinderMAUI/Platforms/Android/MainApplication.cs
  PetFinderMAUI/PetFinderMAUI/Platforms/MacCatalyst/AppDelegate.cs
  PetFinderMAUI/PetFinderMAUI/Platforms/MacCatalyst/Info.plist
  PetFinderMAUI/PetFinderMAUI/Platforms/MacCatalyst/Program.cs
  PetFinderMAUI/PetFinderMAUI/Platforms/Tizen/tizen-manifest.xml
  PetFinderMAUI/PetFinderMAUI/Platforms/Windows/App.xaml
  PetFinderMAUI/PetFinderMAUI/Platforms/Windows/App.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Platforms/Windows/Package.appxmanifest
  PetFinderMAUI/PetFinderMAUI/Platforms/Windows/app.manifest
  PetFinderMAUI/PetFinderMAUI/Platforms/iOS/AppDelegate.cs
  PetFinderMAUI/PetFinderMAUI/Platforms/iOS/Info.plist
  PetFinderMAUI/PetFinderMAUI/Platforms/iOS/Program.cs
  PetFinderMAUI/PetFinderMAUI/Resources/Images/Icons/female.png
  PetFinderMAUI/PetFinderMAUI/Resources/Images/Icons/male.png
  PetFinderMAUI/PetFinderMAUI/Resources/Styles/Colors.xaml
  PetFinderMAUI/PetFinderMAUI/Resources/Styles/Styles.xaml
  PetFinderMAUI/PetFinderMAUI/Utils/GlobalHelper.cs
  PetFinderMAUI/PetFinderMAUI/ViewModels/LoginViewModel.cs
  PetFinderMAUI/PetFinderMAUI/ViewModels/RegisterViewModel.cs
Labels: bug, enhancement

#27 app performance improvement
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
Labels: bug

#32 Bugs fixes
  PetFinderMAUI/PetFinderMAUI/Entities/User.cs
  PetFinderMAUI/PetFinderMAUI/Pages/AboutPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/AboutPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/AboutPetPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/AboutPetPage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/ViewModels/RegisterViewModel.cs
Labels: bug, enhancement

#38 edit comment
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml
Labels: bug

#41 Impl of Profile page #40
  PetFinderMAUI/PetFinderMAUI/Pages/ProfilePage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/ProfilePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/SettingsPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/SettingsPage.xaml.cs
Labels: enhancement

#42 UI enhancement & colors changes
  PetFinderMAUI/PetFinderMAUI/AppShell.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/WelcomePage.xaml
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
  PetFinderMAUI/PetFinderMAUI/Platforms/Android/Resources/values/colors.xml
  PetFinderMAUI/PetFinderMAUI/Resources/Styles/Colors.xaml
  PetFinderMAUI/PetFinderMAUI/ViewModels/RegisterViewModel.cs
Labels: enhancement

#44 Fixed loading progress bar #43
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml
  PetFinderMAUI/PetFinderMAUI/ViewModels/LoginViewModel.cs
  PetFinderMAUI/PetFinderMAUI/ViewModels/RegisterViewModel.cs
Labels: bug

#46 bug's fixed #45
  PetFinderMAUI/PetFinderMAUI/App.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/ProfilePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml
  PetFinderMAUI/PetFinderMAUI/Resources/AppIcon/backgroundicon.svg
  PetFinderMAUI/PetFinderMAUI/Resources/AppIcon/defaultappicon.svg
  PetFinderMAUI/PetFinderMAUI/ViewModels/LoginViewModel.cs
  PetFinderMAUI/PetFinderMAUI/ViewModels/RegisterViewModel.cs
Labels: bug, enhancement

#48 design
  PetFinderMAUI/.idea/.idea.PetFinderMAUI/.idea/deploymentTargetDropDown.xml
  PetFinderMAUI/PetFinderMAUI/Pages/LoginPage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/SignUpPage.xaml
Labels: help wanted

#52 Impl firebase db on home page & UI Improvement ✨
  PetFinderMAUI/.idea/.idea.PetFinderMAUI/.idea/deploymentTargetDropDown.xml
  PetFinderMAUI/PetFinderMAUI/AppShell.xaml
  PetFinderMAUI/PetFinderMAUI/Entities/Pet.cs
  PetFinderMAUI/PetFinderMAUI/Pages/HomePage.xaml
  PetFinderMAUI/PetFinderMAUI/Pages/HomePage.xaml.cs
  PetFinderMAUI/PetFinderMAUI/PetFinderMAUI.csproj
  PetFinderMAUI/PetFinderMAUI/Resources/AppIcon/foregroundicon.svg
  PetFinderMAUI/PetFinderMAUI/Resources/Images/bghome.svg
  PetFinderMAUI/PetFinderMAUI/ViewModels/PetViewModel.cs
  PetFinderMAUI/PetFinderMAUI/Views/PetCard.xaml
  PetFinderMAUI/PetFinderMAUI/Views/PetCard.xaml.cs
Labels: enhancement
